version: '3'
services:
  web:
    image: ywateba/wordpress
    container_name: wordpress_web
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: blog_db_name
      WORDPRESS_CONFIG_EXTRA: |
        /* If you want to add any extra wordpress config */
        # define('WP_ALLOW_MULTISITE', true );
    volumes:
      - wordpress:/var/www/html:rw
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: blog_db_name
    volumes:
      - wordpress_db:/var/lib/mysql
volumes:
  wordpress:
    name: "wordpress"
  wordpress_db:
    name: "wordpress_db"